CC = gcc
CC_FLAGS = -ggdb

all:
	$(CC) shell_sort.c heap_sort.c quick_sort.c merge_sort.c \
		selection_sort.c bubble_sort.c insertion_sort.c \
		my_utl.c sorting_test.c -o sorting_test
clean:
	rm -f sorting_test
